### ISSUE TITLE
Atom feeds being ignored

### ISSUE THREAD

**Issue by larryprice** [codatory/indyhackers.org-planet#13]
`Feeds.to_a` only returns feeds which Feedjira interprets as RSS feeds. Because of this, `entries` is discarding about half of the sites listed in `config.yml`.

Is this undesired behavior? I have a patch I'll submit as a PR shortly.

**Comment by codatory** [comment]
Huh; I thought I was seeing fewer posts than I expected. Thanks for tracking that down! I'll pull down your PR and verify it.

**Comment by codatory** [comment]
Seems like it's working fine, I'll go ahead and close this issue.
